// src/renderer/src/layout/sider/index.vue
<template>
  <n-menu :options="menuOptions" :value="route.path"></n-menu>
</template>

<script lang="ts" setup>
import { MenuOption, NIcon } from 'naive-ui'
import {
  FireOutlined,
  PlayCircleOutlined,
  HeartOutlined,
  HistoryOutlined,
  SettingOutlined,
  StarOutlined
} from '@vicons/antd'
import { Component, h } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'

const route = useRoute()
const router = useRouter()

function renderIcon(icon: Component) {
  return () => h(NIcon, null, { default: () => h(icon) })
}

const menuOptions: MenuOption[] = [
  {
    label: () => h(RouterLink, { to: '/recommend' }, { default: () => '推荐' }),
    key: '/recommend',
    icon: renderIcon(FireOutlined)
  },
  {
    label: () => h(RouterLink, { to: '/iptv' }, { default: () => '直播' }),
    key: '/iptv',
    icon: renderIcon(PlayCircleOutlined)
  },
  {
    label: () => h(RouterLink, { to: '/collect' }, { default: () => '收藏' }),
    key: '/collect',
    icon: renderIcon(HeartOutlined)
  },
  {
    label: () => h(RouterLink, { to: '/history' }, { default: () => '历史' }),
    key: '/history',
    icon: renderIcon(HistoryOutlined)
  },
  {
    label: () => h(RouterLink, { to: '/setting' }, { default: () => '设置' }),
    key: '/setting',
    icon: renderIcon(SettingOutlined)
  },
  {
    label: () => h(RouterLink, { to: '/about' }, { default: () => '关于' }),
    key: '/about',
    icon: renderIcon(StarOutlined)
  }
]
</script>

// src/renderer/src/components/layout/sider/index.tsx
import { Menu } from 'antd'
import {
  FireOutlined,
  HistoryOutlined,
  HeartOutlined,
  StarOutlined,
  PlayCircleOutlined,
  SettingOutlined
} from '@ant-design/icons'
import { Link } from 'react-router-dom'
import './index.less'
import store from '../../../store'

export default function TomatoxSider(): JSX.Element {
  const { theme } = store

  return (
    <>
      <Menu
        defaultSelectedKeys={['/recommend']}
        theme={theme}
        mode={'vertical'}
        style={{ height: '100%' }}
      >
        <Menu.Item key={'/recommend'} icon={<FireOutlined />}>
          <Link to={'/recommend'}>
            <span>推荐</span>
          </Link>
        </Menu.Item>
        <Menu.Item key={'/iptv'} icon={<PlayCircleOutlined />}>
          <Link to={'/iptv'}>
            <span>直播</span>
          </Link>
        </Menu.Item>
        <Menu.Item key={'/history'} icon={<HistoryOutlined />}>
          <Link to={'/history'}>
            <span>历史</span>
          </Link>
        </Menu.Item>
        <Menu.Item key={'/collect'} icon={<HeartOutlined />}>
          <Link to={'/collect'}>
            <span>收藏</span>
          </Link>
        </Menu.Item>
        <Menu.Item key={'/setting'} icon={<SettingOutlined />}>
          <Link to={'/setting'}>
            <span>设置</span>
          </Link>
        </Menu.Item>
        <Menu.Item key={'/about'} icon={<StarOutlined />}>
          <Link to={'/about'}>
            <span>关于</span>
          </Link>
        </Menu.Item>
      </Menu>
    </>
  )
}
